(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
function em1(){var c="ufbnA7t/tuvejp";var addr="mailto:";for(var i=0;i<c.length;i++)addr+=String.fromCharCode(c.charCodeAt(i)-1);window.location.href=addr;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/6s-logo-356.png':'images/6s-logo-178.png');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?'images/6s-logo-white-516.png':'images/6s-logo-white-258.png');
var a='data-src';var e=document.querySelector('.un3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-white-124-1.png':'images/6s-logo-white-62-1.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/6s-logo-black-230.png':'images/6s-logo-black-115.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-black-266.png':'images/6s-logo-black-133.png');}else if($(window).width()>=960){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/6s-logo-284.png':'images/6s-logo-142.png');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?'images/6s-logo-white-412.png':'images/6s-logo-white-206.png');
var a='data-src';var e=document.querySelector('.un3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-white-98.png':'images/6s-logo-white-49.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/6s-logo-black-184.png':'images/6s-logo-black-92.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-black-214.png':'images/6s-logo-black-107.png');}else if($(window).width()>=768){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/6s-logo-230.png':'images/6s-logo-115.png');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?'images/6s-logo-white-332.png':'images/6s-logo-white-166.png');
var a='data-src';var e=document.querySelector('.un3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-white-78.png':'images/6s-logo-white-39.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/6s-logo-black-148.png':'images/6s-logo-black-74.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-black-172.png':'images/6s-logo-black-86.png');}else if($(window).width()>=480){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/6s-logo-256.png':'images/6s-logo-128.png');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?'images/6s-logo-white-494.png':'images/6s-logo-white-247.png');
var a='data-src';var e=document.querySelector('.un3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-white-186.png':'images/6s-logo-white-93.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/6s-logo-black-90.png':'images/6s-logo-black-45.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-black-246.png':'images/6s-logo-black-123.png');}else{var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/6s-logo-170.png':'images/6s-logo-85.png');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?'images/6s-logo-white-330.png':'images/6s-logo-white-165.png');
var a='data-src';var e=document.querySelector('.un3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-white-124.png':'images/6s-logo-white-62.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/6s-logo-black-60.png':'images/6s-logo-black-30.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6s-logo-black-164.png':'images/6s-logo-black-82.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)');[].forEach.call(e,function(e){e.addEventListener("click",function(o){var t=0;if(e.hash.length>1){var n=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));n||(n=1);var l=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];t=(l.getBoundingClientRect().top+pageYOffset)*n}if("scrollBehavior"in document.documentElement.style)scroll({top:t,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(o){a||(a=o);var n=o-a;scrollTo(0,r<t?(t-r)*n/400+r:r-(r-t)*n/400),n<400?requestAnimationFrame(e):scrollTo(0,t)})}else scrollTo(0,t);o.preventDefault()},!1)})}();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un26 source');ldsrcset('.un27 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}